spring.application.name=weather

spring.data.redis.host=localhost
spring.data.redis.port=6379

api.key.weather=${API_KEY}

# Rate Limit
resilience4j.ratelimiter.instances.search.limit-for-period=2
resilience4j.ratelimiter.instances.search.limit-refresh-period=30s
resilience4j.ratelimiter.instances.search.timeout-duration=0
